### ISSUE TITLE
Total Locked Collateral and Total Minted IST graphs missing some assets

### ISSUE THREAD

**Issue by otoole-brendan** [agoric-labs/agoric-inter-dashboard#83]
The DCF noticed some strange behavior in two graphs on info.inter.trade despite those assets appearing present in Vaults.

Total Locked Collateral and Total Minted IST are missing stATOM, ATOM and stOSMO on 6/16 and 6/22.
Also,
on 6/17 and 6/23- stATOM is missing
on 6/19, 6/20 and 6/24 stOSMO is missing
on 6/21 and 6/23 stATOM is missing
Screenshot:

<img width="1139" alt="image" src="https://github.com/agoric-labs/agoric-inter-dashboard/assets/93355546/d759af0f-81a7-4462-812d-cef57b07c735">

**Comment by frazarshad** [comment]
The graphs shown above use our daily snapshots of vault manager metrics.

A daily snapshot of vault manager metrics is created whenever the metrics data is updated. On days when this data is not updated, a snapshot is not created

This behaviour of "missing snapshots" is expected and to account for this, we interpolate the data since if a snapshot exists for day 1 and day 5 but not for 2,3 and 4, these missing days will have the same value as day 1.

The logic for handling this on the frontend is not working as expected. A [PR](https://github.com/agoric-labs/agoric-inter-dashboard/pull/84) has been opened to fix this
